env:
  JAVA_HOME: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"

steps:
  - label: "Build"
    command: "./gradlew :library:clean :library:assembleRelease :library:assembleDebug"
    agents:
      - "queue=link-tablet"

  - label: "Publish artifacts"
    command: "./gradlew :library:artifactoryPublish"
    branches: "master"
    artifact_paths:
      - "library/build/outputs/aar/google-maps-clustering-release.aar"
      - "library/build/outputs/aar/google-maps-clustering-debug.aar"
