env:
  JAVA_HOME: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"

steps:
  - label: "Build"
    command: "./gradlew :library:clean :library:assembleRelease :library:assembleDebug"
    agents:
      - "queue=link-tablet"
    artifact_paths:
      - "library/build/outputs/aar/library-release.aar"
      - "library/build/outputs/aar/library-debug.aar"

  - label: "Publish artifacts"
    command: "./gradlew :library:artifactoryPublish"
    branches: "master"
    agents:
      - "queue=link-tablet"